### PR TITLE
Feature: Document Encryption

### PR DESCRIPTION
**Pull request by PhakornKiong**
Document encryption feature development under #243, 

- Able to encrypt newly created document  using PDFWriter
- Still facing issue with PDFStreamWriter (Need some input on this area)
- Pending discussion on whether to handle creation of `Security` object at `PDFDocument.create()` or `PDFDocument.encrypt()`

To test, run `yarn scratchpad:run` and open the PDF.

I was able to implement this feature thanks to the `security` module from `pdfkit`

@Hopding 
Appreciate it if you could provide some feedback or ideas on how to maintain the consistency of code with the library.

### CODE REVIEW

**Comment by Darkripper214** [comment]
Update 1:

Added `PDFDocument.encrypt()` as it makes more sense to apply encrypt separately to support encryption for New & Existing Document.

You can try this here.
```Javascript

  const existingPdfBytes = fs.readFileSync('assets/pdfs/sample_form.pdf');

  // Load a PDFDocument without updating its existing metadata
  const pdfDoc = await PDFDocument.load(existingPdfBytes);
  await pdfDoc.encrypt({
    encryptOption: {
      userPassword: 'abcd',
    },
  });

  const pdfBytes = await pdfDoc.save({ useObjectStreams: false });
  fs.writeFileSync('out.pdf', pdfBytes);
  openPdf('out.pdf', Reader.Preview);
```

**Comment by Darkripper214** [comment]
Update 2:

Change usage of `Buffer` Class to `Uint8Array` when applicable (To ensure browser compatibility)
Moved Encryption of Indirect Object to occur when Counting Buffer Size for accurate buffer size

The encrypt function should works for both new and existing file using `PDFWriter`

I'm still figuring out how would it works with `Stream Object`

**Comment by Darkripper214** [comment]
Update 3:
The feature should work for both `PDFWriter` and `PDFStreamWriter`.

The issue I was facing on `PDFStreamWriter` is actually I went and encrypt the `Cross-Reference Stream` (Which shouldn't be encrypted).

I've clean up the code a little bit with some initial description on how `PDFSecurity` class works.

**Comment by azizahmed45** [comment]
Encrypted pdf not opening on Adobe Acrobat Reader Dc and other versions of Adobe reader.
The error massage is "there was an error opening this document. the file is damaged and could not be repaired"

**Comment by PhakornKiong** [comment]
> Encrypted pdf not opening on Adobe Acrobat Reader Dc and other versions of Adobe reader.
> The error massage is "there was an error opening this document. the file is damaged and could not be repaired"

Could you provide more details? Best in a reproduce-able repo.

It might be due to `streamWriter`

**Comment by azizahmed45** [comment]
> > Encrypted pdf not opening on Adobe Acrobat Reader Dc and other versions of Adobe reader.
> > The error massage is "there was an error opening this document. the file is damaged and could not be repaired"
> 
> Could you provide more details? Best in a reproduce-able repo.
> 
> It might be due to `streamWriter`

I didn't understood. Which kind of details you needed. 
When I use the `doc.encrypt()` the output file does not open by the Adobe Acrobat reader. But works with other Readers Like Chrome, Foxit Reader.

**Comment by PhakornKiong** [comment]
> > > Encrypted pdf not opening on Adobe Acrobat Reader Dc and other versions of Adobe reader.
> > > The error massage is "there was an error opening this document. the file is damaged and could not be repaired"
> > 
> > 
> > Could you provide more details? Best in a reproduce-able repo.
> > It might be due to `streamWriter`
> 
> I didn't understood. Which kind of details you needed.
> When I use the `doc.encrypt()` the output file does not open by the Adobe Acrobat reader. But works with other Readers Like Chrome, Foxit Reader.

Like the content of the PDF that gets encrypted but does not render. Else how would one troubleshoot?

**Comment by azizahmed45** [comment]
> > > > Encrypted pdf not opening on Adobe Acrobat Reader Dc and other versions of Adobe reader.
> > > > The error massage is "there was an error opening this document. the file is damaged and could not be repaired"
> > > 
> > > 
> > > Could you provide more details? Best in a reproduce-able repo.
> > > It might be due to `streamWriter`
> > 
> > 
> > I didn't understood. Which kind of details you needed.
> > When I use the `doc.encrypt()` the output file does not open by the Adobe Acrobat reader. But works with other Readers Like Chrome, Foxit Reader.
> 
> Like the content of the PDF that gets encrypted but does not render. Else how would one troubleshoot?

Original File: [https://drive.google.com/file/d/1QQpnJ0bygGVdjrRvn2kLUvB4XqfDbV7t/view?usp=sharing](https://drive.google.com/file/d/1QQpnJ0bygGVdjrRvn2kLUvB4XqfDbV7t/view?usp=sharing)

Edited and Encrypted File: [https://drive.google.com/file/d/1N_RKyv2KxnydFj4_26jWH9N_ceLmM8lW/view?usp=sharing](https://drive.google.com/file/d/1N_RKyv2KxnydFj4_26jWH9N_ceLmM8lW/view?usp=sharing)

Password: `"password"`

Edited and Encrypted file not opening on Adobe Acrobat Reader DC, with other Readers are working fine.
The issue happens only when I try to encrypt pdf.

**Comment by PhakornKiong** [comment]
> > > > > Encrypted pdf not opening on Adobe Acrobat Reader Dc and other versions of Adobe reader.
> > > > > The error massage is "there was an error opening this document. the file is damaged and could not be repaired"
> > > > 
> > > > 
> > > > Could you provide more details? Best in a reproduce-able repo.
> > > > It might be due to `streamWriter`
> > > 
> > > 
> > > I didn't understood. Which kind of details you needed.
> > > When I use the `doc.encrypt()` the output file does not open by the Adobe Acrobat reader. But works with other Readers Like Chrome, Foxit Reader.
> > 
> > 
> > Like the content of the PDF that gets encrypted but does not render. Else how would one troubleshoot?
> 
> Original File: https://drive.google.com/file/d/1QQpnJ0bygGVdjrRvn2kLUvB4XqfDbV7t/view?usp=sharing
> 
> Edited and Encrypted File: https://drive.google.com/file/d/1N_RKyv2KxnydFj4_26jWH9N_ceLmM8lW/view?usp=sharing
> 
> Password: `"password"`
> 
> Edited and Encrypted file not opening on Adobe Acrobat Reader DC, with other Readers are working fine.
> The issue happens only when I try to encrypt pdf.

Try to use non-stream writer and see if error persist.
`const pdfBytes = await pdfDoc.save({ useObjectStreams: false });`

I'm suspecting something is not 100% correct on the stream writer. Will take a while to investigate on it.

**Comment by azizahmed45** [comment]
> const pdfBytes = await pdfDoc.save({ useObjectStreams: false });

`const pdfBytes = await pdfDoc.save({ useObjectStreams: false });`

This solved the issue.

**Comment by PhakornKiong** [comment]
> > const pdfBytes = await pdfDoc.save({ useObjectStreams: false });
> 
> `const pdfBytes = await pdfDoc.save({ useObjectStreams: false });`
> 
> This solved the issue.

I suspect there is something amiss with the `xref` table, it could be that the the byte offset is messed. Maybe we could just roll this feature out without using stream while trying to figure out this part.

Appreciate if anyone could lend a hand on this part.

**Comment by Hopding** [comment]
Hello @PhakornKiong! Thanks so much for working on this! Apologies for my late response. I've been very busy these past few months taking care of some personal stuff and starting my new job at GitHub 🙂 

I'm hoping to get around to reviewing this PR in the next few weeks now that I've got some more free time.

Please note that you'll need to either update this PR (via a force push) or open a new PR with your changes. The tl;dr is that I recently had to do a fairly extensive git history rewrite that caused a bunch of conflicts. Please read https://github.com/Hopding/pdf-lib#git-history-rewrite for details. Apologies for the hassle!

**Comment by Psycc** [comment]
Heii,
thank you @PhakornKiong for your work. I wanted to implement this PR as UMD, but I got the following error. Can you help me out?

`TypeError: Cannot read properties of undefined (reading 'readFileSync')`

**Comment by PhakornKiong** [comment]
> Heii,
> thank you @PhakornKiong for your work. I wanted to implement this PR as UMD, but I got the following error. Can you help me out?
> 
> `TypeError: Cannot read properties of undefined (reading 'readFileSync')`

I think the error is due to the usage of `fs.readFileSync` which is a node.js module. I used it in `scratchpad` just for ease of testing.

```
import fs from 'fs';
...
const existingPdfBytes = fs.readFileSync('assets/pdfs/sample_form.pdf');
```
It should work if you just change that part to load the file accordingly.

**Comment by Psycc** [comment]
@PhakornKiong I checked it again, comment this out and then build it again. I think i looked at the wrong error. When he tries to build the pdf-lib-min.js, he get the following errors.

`(!) Missing shims for Node.js built-ins
Creating a browser bundle that depends on 'path'. You might need to include https://github.com/ionic-team/rollup-plugin-node-polyfills
(!) Unresolved dependencies
https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency
crypto (imported by node_modules/crypto-js/core.js, crypto?commonjs-external)
fs (imported by node_modules/saslprep/lib/memory-code-points.js, fs?commonjs-external)
path (imported by node_modules/saslprep/lib/memory-code-points.js, path?commonjs-external)
(!) Missing global variable names
Use output.globals to specify browser global variable names corresponding to external modules
crypto (guessing 'crypto')
fs (guessing 'fs')
path (guessing 'path')`

**Comment by PhakornKiong** [comment]
> @PhakornKiong I checked it again, comment this out and then build it again. I think i looked at the wrong error. When he tries to build the pdf-lib-min.js, he get the following errors.
> 
> `(!) Missing shims for Node.js built-ins
> Creating a browser bundle that depends on 'path'. You might need to include https://github.com/ionic-team/rollup-plugin-node-polyfills
> 
> (!) Unresolved dependencies
> https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency
> crypto (imported by node_modules/crypto-js/core.js, crypto?commonjs-external)
> fs (imported by node_modules/saslprep/lib/memory-code-points.js, fs?commonjs-external)
> path (imported by node_modules/saslprep/lib/memory-code-points.js, path?commonjs-external)
> 
> (!) Missing global variable names
> Use output.globals to specify browser global variable names corresponding to external modules
> crypto (guessing 'crypto')
> fs (guessing 'fs')
> path (guessing 'path')`

@Psycc can you confirm if you've excluded the entire `scratchpad` folder from the build? since that is for local testing only (And the location where `fs` and `path` was used.

For crypto, I used `"crypto-js": "^4.0.0"` as written in `package.json` depdency. 

Btw I don't think this is the best place to help you on this issue (Don't want to pollute non-review stuff in this PR), maybe you can create a separate issue and we'll catch up from there.

**Comment by Hopding** [comment]
@PhakornKiong appreciate the effort you put into this. If you're still interested in getting this shipped, feel free to open a new PR (per my previous comment) and we can go from there 🙂. (The diff for this PR has 700+ changes).

**Comment by PhakornKiong** [comment]
@Hopding No worries, I will re-open the PR again once I fix the UMD build thingy that requires some manual porting. Kinda occupied with work atm.

**Comment by freakfan15** [comment]
> > > const pdfBytes = await pdfDoc.save({ useObjectStreams: false });
> > 
> > 
> > `const pdfBytes = await pdfDoc.save({ useObjectStreams: false });`
> > This solved the issue.
> 
> I suspect there is something amiss with the `xref` table, it could be that the the byte offset is messed. Maybe we could just roll this feature out without using stream while trying to figure out this part.
> 
> Appreciate if anyone could lend a hand on this part.

Hi @PhakornKiong. This works but breaks the pdf in a way. Like if I use useObjectStreams: false, the opacity of the table of content section becomes 0. It's there I can click on it but can't see it. Even the pdf title changes to some random text. 
Is this a known issue?

**Comment by rahul-boinepally** [comment]
@freakfan15 - how did you manage to add encryption method to pdflib ? is it when instantiating or as a param when saving it ? thanks

**Comment by GibranValle** [comment]
Hi @PhakornKiong, I was trying to use your branch with this command 
`yarn add pdf-lib@https://github.com/PhakornKiong/pdf-lib#dev/DocEncrypt`
However I cannot import the module after this modification. Any sugestions? 
thanks.

**Pull request closed without merging**
