### PR TITLE
Feature/draw line cap style

### PR DESCRIPTION
**Pull request by taxilian**
Simple PR; just wanted to be able to set the line cap style when drawing a line

### CODE REVIEW

**Comment by Hopding** [comment]
Looks good. Thanks @taxilian!

**Comment by Hopding** [comment]
Version [`1.6.0`](https://www.npmjs.com/package/pdf-lib/v/1.6.0) is now published with this feature. The full release notes are available [here](https://github.com/Hopding/pdf-lib/releases/tag/v1.6.0).

You can install this new version with npm:

```
npm install pdf-lib@1.6.0
```

It's also available on unpkg:

- https://unpkg.com/pdf-lib@1.6.0/dist/pdf-lib.js
- https://unpkg.com/pdf-lib@1.6.0/dist/pdf-lib.min.js

As well as jsDelivr:

- https://cdn.jsdelivr.net/npm/pdf-lib@1.6.0/dist/pdf-lib.js
- https://cdn.jsdelivr.net/npm/pdf-lib@1.6.0/dist/pdf-lib.min.js

**Comment by antoinerousseau** [comment]
Sorry I'm late to the party, but was the breaking change necessary? (required prop)
Couldn't we have `lineCap?: LineCapStyle;` instead of `lineCap: LineCapStyle | undefined;`?

**Comment by Hopding** [comment]
Hello @antoinerousseau!

You’re absolutely correct. This addition should not have introduced a breaking change. The new prop should be optional. My apologies, I should’ve caught this before releasing. I’ll publish a patch for this as `1.6.1` as soon as I get back to my desk today. Thanks for calling this out!

**Comment by antoinerousseau** [comment]
Ok cool, and no worries!

**Comment by taxilian** [comment]
My apologies; I was following what appeared to be the conventions of the file =] I'll be more careful next time.

**Comment by Hopding** [comment]
@taxilian No worries! You did follow the correct conventions for the files you changed. Unfortunately, in order to avoid a breaking API change it's necessary to violate those conventions. Try as we might, it's quite difficult to prevent these little things from slipping though now and again.

**Comment by Hopding** [comment]
@antoinerousseau Version [`1.6.1`](https://www.npmjs.com/package/pdf-lib/v/1.6.1) is now published. It contains the fix for this issue. The full release notes are available [here](https://github.com/Hopding/pdf-lib/releases/tag/v1.6.1).

You can install this new version with npm:

```
npm install pdf-lib@1.6.1
```

It's also available on unpkg:

- https://unpkg.com/pdf-lib@1.6.1/dist/pdf-lib.js
- https://unpkg.com/pdf-lib@1.6.1/dist/pdf-lib.min.js

As well as jsDelivr:

- https://cdn.jsdelivr.net/npm/pdf-lib@1.6.1/dist/pdf-lib.js
- https://cdn.jsdelivr.net/npm/pdf-lib@1.6.1/dist/pdf-lib.min.js

**Comment by antoinerousseau** [comment]
wow that was fast, thanks!

**Pull request merged**
