### PR TITLE
Add place at back

### PR DESCRIPTION
**Pull request by Techno11**
## What?

Add ability to place drawn PDFPage elements in the back as opposed to the front

## Why?

I needed the ability to draw page elements behind elements that I've already drawn.

## How?

If the flag placeInBack is set on any drawable pdf element (like rectange, circle, etc) the drawn object is spliced into array position 0 of the content stream, rather than pushed to the end of the array.

## Testing?

I have tested drawing with all objects and ran the CI.

## New Dependencies?

N/A

## Screenshots

image
The red rectangle was drawn after the text that is on top of it

## Suggested Reading?

Yes

## Anything Else?

N/A

## Checklist
- [X] I read [CONTRIBUTING.md](https://github.com/Hopding/pdf-lib/blob/master/docs/CONTRIBUTING.md).
- [X] I read [MAINTAINERSHIP.md#pull-requests](https://github.com/Hopding/pdf-lib/blob/master/docs/MAINTAINERSHIP.md#pull-requests).
- [x] I added/updated unit tests for my changes.
- [x] I added/updated integration tests for my changes.
- [X] I [ran the integration tests](https://github.com/Hopding/pdf-lib/blob/master/docs/CONTRIBUTING.md#running-the-integration-tests).
- [X] I tested my changes in Node, Deno, and the browser.
- [X] I viewed documents produced with my changes in Adobe Acrobat, Foxit Reader, Firefox, and Chrome.
- [X] I added/updated doc comments for any new/modified public APIs.
- [X] My changes work for both **new** and **existing** PDF files.
- [X] I [ran the linter](https://github.com/Hopding/pdf-lib/blob/master/docs/CONTRIBUTING.md#running-the-linter) on my changes.

### CODE REVIEW

**Review by Hopding — CHANGES_REQUESTED** [review]
Hello @Techno11! This is a cool idea! Thanks for making a PR 😃.

A couple things I'd like to change before merging:
* The term `placeAtBack` isn't ideal for search indexing, and I suspect many users will find it unintuitive. Naming is hard, but I think `underneath` will be more indexable and intuitive. (`behind` and `below` are two other alternatives that come to mind).
* Please update an existing integration test to showcase this behavior for 2 or three of the `PDFPage` methods you've updated.
* Please update the [`PDFContentStream.spec.ts`](https://github.com/Hopding/pdf-lib/blob/master/tests/core/structures/PDFContentStream.spec.ts) file to test the new `.splice(...)` method.

**Comment by Techno11** [comment]
Hi @Hopding, thanks for the quick review. I added the .splice() to the spec file, as well as added a 6th page to test1, which looks like the following:
image


Here is the full PDF of the modified test1
[pdf_with_drawBehind_objs.pdf](https://github.com/Hopding/pdf-lib/files/7453906/pdf_with_drawBehind_objs.pdf)

Lastly, (I forgot to include this in the original comment) this implements and closes #251 
(even though it is stale and has already been closed)

**Comment by Hopding** [comment]
@Techno11 thanks for making the changes! Can you please explain how this functionality works when used on an existing PDF file and update a second integration test to demonstrate this?

**Comment by chebum** [comment]
@Hopding I believe the suggested approach won't work when modifying existing document: PDFPage.getContentStream() inserts the newly created content stream on top of the page existing content: 

    this.node.addContentStream(this.contentStreamRef);

Should one need to insert an image before existing content, this code can be used:

    page.drawImage(imageRef, { /* x, y, width, height */ });
    const contents = page.node.normalizedEntries().Contents;
    const newContentsRef = contents.get(contents.size() - 1);
    contents.remove(contents.size() - 1);
    contents.insert(0, newContentsRef);

It works with current version of pdf-lib. No modifications necessary.

**Comment by Techno11** [comment]
Closing as the above solution works. Thanks!

**Pull request closed without merging**
