### PR TITLE
Compute multiline font size for multiline inputs

### PR DESCRIPTION
**Pull request by milesnash**
Addresses lack of support for multiline input automatic font sizing, as described in #910 

Ran through the testing as described in CONTRIBUTING.md.  All looked good to me.

### CODE REVIEW

**Comment by milesnash** [comment]
Hi @Hopding, sorry to DM, would you or another reviewer mind taking a look at this?  Do you think these proposed changes are sensible?  I did consider tests as well but felt like the functionality was already adequately covered by the visual testing described in CONTRIBUTING.md (in particular by the "Backstory" input field of test15), would you agree?

**Comment by Hopding** [comment]
Hello @milesnash! Thanks so much for working on this! Apologies for my late response. I've been very busy these past few months taking care of some personal stuff and starting my new job at GitHub 🙂 

I'm hoping to get around to reviewing this PR in the next few weeks now that I've got some more free time.

Please note that you'll need to either update this PR (via a force push) or open a new PR with your changes. The tl;dr is that I recently had to do a fairly extensive git history rewrite that caused a bunch of conflicts. Please read https://github.com/Hopding/pdf-lib#git-history-rewrite for details. Apologies for the hassle!

**Comment by milesnash** [comment]
Hey @Hopding , no worries, thanks for getting back to me and congrats on your new role! I'll get the PR fixed up and update you when it's ready 👍

**Comment by milesnash** [comment]
Closing in order to re-fork and reopen as per advice in previous comment.

**Pull request closed without merging**
